server:
  port: 8989
  servlet:
    jsp:
      init-parameters:
        development: true
    context-path: /cmfz
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp

    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mappers/*Mapper.xml
logging:
  level:
    root: info
    com.baizhi.dao: debug
    com.baizhi.service: debug
    com.baizhi.controller: debug
